### ISSUE TITLE
Error when try to run app.js

### ISSUE THREAD

**Issue by vrusua** [devshelf/devshelf-articles#74]
How to run the app.js? I got the error:
 
TypeError: Cannot call method 'map' of undefined
    at /Users/owlookit/_dev/_localhost/dh/core/generate-data.js:95:15
    at Object.oncomplete (fs.js:107:15)

Thanks a lot in advance,
Ruslan

**Comment by operatino** [comment]
Hi, 

Most likely it's related to missing articles folder, which you set-up in `core/options/default-options.js`. The easiest way to configure it, will be to symlink `devshelf-articles` repo to `devshelf/articles-data` folder. Also be aware, that some features require private github and prerenderToken tokens.

I still didn't found time to write down set-up instructions, but it's on the way! Until that, you can ask related questions in this topic https://github.com/devshelf/devshelf/issues/4.

I will close the task here, because it's not located in core repo. Devshelf-articles contains only data for the site.
